server:
  zipkin:
    base-url: http://192.168.60.3:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  servlet:
    session:
      timeout: 30m
  port: 20000
spring:
  session:
    store-type: redis
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.60.3:8858
    nacos:
      discovery: 
        service: gulimall-auth-server
        server-addr: 192.168.60.100:1111
  thymeleaf: 
    cache: false
  redis:
    host: 192.168.60.10
    password: 123456
    port: 6379
ribbon:
  ReadTimeout: 50000

gitee:
  clientsecret: 0fc78caec70cc28db68bd098af6d83fbed106363b17f426c996f7c42be63e9e6
  
management: 
  endpoints:  
    web: 
      exposure: 
        include: '*'