server:
  servlet:
    session:
      timeout: 30m
  port: 20000
spring:
  session:
    store-type: redis
  cloud:
    nacos:
      discovery: 
        service: gulimall-auth-server
        server-addr: #nacos的地址
  thymeleaf: 
    cache: false
  redis:
    host: 192.168.60.10
    password: 123456
    port: 6379
ribbon:
  ReadTimeout: 50000

gitee:
  clientsecret: #gitee的第三方密码
  