server:
  port: 40000
spring: 
  zipkin:
    base-url: http://192.168.60.3:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  session:
    store-type: redis
  redis:
    host: 192.168.60.10
    password: 123456
    port: 6379
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.60.3:8858
    nacos:
      discovery: 
        service: gulimall-cart
        server-addr: 192.168.60.100:1111
  thymeleaf: 
    cache: false

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

management: 
  endpoints:  
    web: 
      exposure: 
        include: '*'