server:
  port: 9010

spring:
  zipkin:
    base-url: http://192.168.60.3:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  session:
    store-type: redis
  thymeleaf: 
    cache: false
  rabbitmq:
    host: 192.168.60.11
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
    username: admin
    password: admin
  redis: 
    host: 192.168.60.10
    password: 123456
    port: 6379
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.60.3:8858
    nacos:
      discovery:
        server-addr: 192.168.60.100:1111
        service: gulimall-order
  datasource:
    username: root
    password: '072900'
    url: jdbc:mysql://192.168.60.9:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

management: 
  endpoints:  
    web: 
      exposure: 
        include: '*'