spring:
  session:
    store-type: redis
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.60.9:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        service: gulimall-product
        server-addr: #nacos地址
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: #redis地址
    password: 123456
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      #建议不指定前缀，默认分区名前缀key-prefix: CACHE_
      use-key-prefix: true
      #是否缓存空值（可防止缓存穿透）
      cache-null-values: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 10000
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
