spring:
  session:
    store-type: redis
  redis:
    host: #redis地址
    password: 123456
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: #nacos地址
        service: gulimall-search
      config:
        enabled: false
  thymeleaf:
    cache: false
server:
  port: 21000